# Generated by Django 4.2.4 on 2023-08-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f'), ('o', 'o')], max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('first_release_year', models.IntegerField()),
                ('no_of_albums_released', models.IntegerField()),
            ],
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=20)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(choices=[('m', 'm'), ('f', 'f'), ('o', 'o')], max_length=15)),
                ('address', models.CharField(max_length=255)),
            ],
            bases=('core.timestampmodel',),
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('timestampmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.timestampmodel')),
                ('title', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('rnb', 'rnb'), ('country', 'country'), ('classic', 'classic'), ('rock', 'rock'), ('jazz', 'jazz')], max_length=15)),
                ('artist_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_music_album', to='cloco_app.artist')),
            ],
            bases=('core.timestampmodel',),
        ),
    ]
