# Generated by Django 4.2.4 on 2023-08-12 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloco_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=datetime.datetime(2023, 8, 12, 13, 15, 21, 889569, tzinfo=datetime.timezone.utc), max_length=150),
            preserve_default=False,
        ),
    ]
