# Generated by Django 3.2.7 on 2023-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloco_app', '0003_auto_20230813_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
